### PR TITLE
Python 3.7 fixes

### PR DESCRIPTION
**Pull request by jsiverskog**
Various fixes I had to make to get pyheatshrink to work with Python 3.7.

### CODE REVIEW

**Comment by jsiverskog** [comment]
The tests fail because it's unable to install Python 3.7. I see that it's running on a very old Ubuntu version, can this be bumped?

**Comment by jsiverskog** [comment]
@dsnipe

**Comment by dsnipe** [comment]
@jsiverskog you could change `.travis.yml` by adding `dist: xenial` (docs: https://docs.travis-ci.com/user/languages/python)
So this should fix CI.
I'll merge the PR then.

**Comment by jsiverskog** [comment]
thanks, done @dsnipe  :)

**Pull request merged**
